- Makefile.in
When building dropbear in a separate directory, 
make install 
will failed to install dropbear.8
Fix it by prepending $(srcdir) to dropbear.8
> Fix installing dropbear.8 error when building in a separate directory.

- keyimport.c
When building dropbear by GCC 4.8.2 in Ubuntu 14.04 amd64, it reported
```
gcc -I../dropbear/libtomcrypt/src/headers/ -I. -I../dropbear  -Os -W -Wall -Wno-pointer-sign -DDROPBEAR_SERVER -DDROPBEAR_CLIENT   -c -o keyimport.o ../dropbear/keyimport.c
../dropbear/keyimport.c: In function ‘openssh_write’:
../dropbear/keyimport.c:1137:10: warning: ‘len’ may be used uninitialized in this function [-Wmaybe-uninitialized]
dropbear_assert(pos == len);
^
../dropbear/keyimport.c:829:26: note: ‘len’ was declared here
int nnumbers = -1, pos, len, seqlen, i;
^
../dropbear/keyimport.c:1137:10: warning: ‘pos’ may be used uninitialized in this function [-Wmaybe-uninitialized]
dropbear_assert(pos == len);
^
../dropbear/keyimport.c:829:21: note: ‘pos’ was declared here
int nnumbers = -1, pos, len, seqlen, i; …
```
> Fix variables may be uninitialized.

- packet.c
When corrupted packet is received negative length of packet can be
displayed.
> minor issue - Integrity error (bad packet size %u) negative length

- debian/dropbear.init
systemd's systemd-sysv-generator uses some of the [init info](http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html) block at the top of the init script, 'Short-Description' being one of them. Since Dropbear is missing this field, systemd displays 'null' in a bunch of places i.e:
```
● dropbear.service - (null)
Loaded: loaded (/etc/init.d/dropbear)
Active: active (running) since Sun 2016-01-03 15:02:36 UTC; 8s ago
Docs: man:systemd-sysv-generator(8)
Jan 03 15:02:36 wily systemd[1]: Starting (null)...
Jan 03 15:02:36 wily dropbear[486]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jan 03 15:02:36 wily dropbear[487]: Running in background
Jan 03 15:02:36 wily systemd[1]: Started (null).
```
And with the extra field:
```
● dropbear.service - …
```
> Added missing Short-Description init info field to debian init script.

- libtomcrypt/Makefile.in
- libtommath/Makefile.in
When building out-of-tree we need both source and generated
folders in include paths to find both distributed and generated
headers.
> Support out-of-tree builds usign bundled libtom

- cli-session.c
- compat.c
- scpmisc.c
_PATH_DEVNULL isn't defined anywhere and was causing issue when porting to a POSIX-like OS.
> Use DROPBEAR_PATH_DEVNULL instead of undefined _PATH_DEVNULL

- termcodes.c
My POSIX-like platform is missing some basic termcodes.
Make them optional.
Signed-off-by: Ben Gardner gardner.ben@gmail.com
> termcodes: make VEOL2, VWERASE, VLNEXT, ECHOCTL, and ECHOKE optional

- configure.ac
Configure options to disable some features, which are checked using
AC_ARG_ENABLE can be invoked with --enable-<option> as well.
The current configure script always generates a #define for such options
even though the --enable-<option> case should not generate a #define.
Fix this by properly checking if the feature should be enabled, in which
case no #define is being generated.
Signed-off-by: Stefan Hauser stefan@shauser.net
> Fix configure options using AC_ARG_ENABLE

- configure.ac
To prevent build failures when using system libtom libraries and
linking with --as-needed, LIBTOM_LIBS should be in the order
-ltomcrypt -ltommath, not the other way around, ie libs should be
prepended to LIBTOM_LIBS as they are found, not appended.
> Fix libtomcrypt/libtommath linking order

- default_options.h
- default_options.h.in
- dropbear.8
- runopts.h
- svr-auth.c
- svr-runopts.c
Add support for '-T n' for a run-time specification for maximum number
of authentication attempts where 'n' is between 1 and compile time
option MAX_AUTH_TRIES.
A default number of tries can be specified at compile time using
'DEFAULT_AUTH_TRIES' which itself defaults to MAX_AUTH_TRIES for
backwards compatibility.
Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>
> dropbear server: support -T max auth tries

- configure.ac
Add mitigations for Spectre v2 attacks.
Spectre:
https://googleprojectzero.blogspot.com/2018/01/reading-privileged-memory-with-side.html
> Add Spectre v2 mitigations for GCC

- svr-authpam.c
This commit introduces fix for scenario:
1. Root login disabled on dropbear
2. PAM authentication model enabled
While login as root user, after prompt for password
user is being notified about login failure, but
after second attempt of prompt for password within
same session, login becomes successful.
Signed-off-by: Pawel Rapkiewicz <pawel.rapkiewicz@gmail.com>
> Fix for issue successful login of disabled user

- packet.c
clean up after 7f15910541
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>
> packet: remove stale comment about "packet_type"

- default_options.h
- svr-agentfwd.c
- svr-auth.c
- svr-authpubkey.c
- svr-chansession.c
Some kernels for embedded devices do not have multiple user support, so setuid() etc will fail. This allows you to login on such a device. It will fail if you attempt to login as a non-root user.
> Support servers without multiple user support

- netio.c
- packet.c
Ad `packet.c` - basically just aligning two #ifdefs - see also https://stackoverflow.com/questions/49187521/packet-c982-error-writebuf-undeclared-first-use-in-this-function
Ad `netio.c` - IOV_MAX is not available in cygwin unless you define _XOPEN_SOURCE to proper value (which has other side effects)
> cygwin competibility fix

- cli-runopts.c
sshfs uses this style of option specification when calling an ssh client. This patch allows dbclient to be used with sshfs -p <portnum>.
> support openssh long option -o Port=XXXX

- keyimport.c
keysizes >= 128 octets will be encoded with a 3 byte header
which must be accounted by the optional-header
Reproduce:
master:~/build/dropbear$ ./dropbearkey -t ecdsa -s 521 -f K
Generating 521 bit ecdsa key, this may take a while...
master:~/build/dropbear$ ./dropbearconvert d o K L
Key is a ecdsa-sha2-nistp521 key
Wrote key to 'L'
master:~/build/dropbear$ openssl ec < L
read EC key
unable to load Key
139769806448384:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:crypto/asn1/asn1_lib.c:91:
> dropbearconvert: keyimport.c: fix BER encoding of secp521r1 keys

- .gitignore
- Makefile.in
- common-session.c
- configure.ac
- default_options.h
- includes.h
- pubkeyapi.h
- runopts.h
- session.h
- svr-authpubkey.c
- svr-runopts.c
- svr-session.c
- sysoptions.h
As discussed over email, I have created an API for dropbear to delegate to an external plugin the public-key authentication.
Description and documentation of the public key API is in: 
([https://github.com/fabriziobertocci/dropbear-epka](https://github.com/fabriziobertocci/dropbear-epka))
Unless enabled during config (--enable-epka), all the changes propsed are ifdef'd out.
Once enabled, it introduces a new command-line argument (-A) to dropbear (server) to dynamically load an external shared library to delegate public-key authentication. 3 examples of plug-in libraries are provided in the ([https://github.com/fabriziobertocci/dropbear-epka](dropbear-epka)) repository.
> External Public-Key Authentication API

- default_options.h
The man page (https://github.com/mkj/dropbear/blob/master/dropbear.8) says MOTD will be printed by default for any login shell, but it was disabled at compile time. Probably happened by accident when this code was moved from `options.h` to `default_options.h`.
> MOTD enabled by default as the manpage says

- gensignkey.c
This PR adds a non-atomic fallback for key generation in instances where using `link()` is not possible.
I hit this issue under Android as most stock Android ROMs block the creation of hard links via SELinux policy but this also covers the case of key generation on filesystems without hard link support.
> Fallback for key generation on systems or filesystems without hard link support

- svr-auth.c
- svr-session.c
Change 'Early exit' and 'Exit before auth' messages to include the IP
address & port as part of the message.
This allows log scanning utilities such as 'fail2ban' to obtain the
offending IP address as part of the failure event instead of extracting
the PID from the message and then scanning the log again for match
'child connection from' messages
Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>
Delimiting with < > may be a step too far... or the whole idea... hence the RFC :-)
> RFC: Improve address logging on early exit messages

- process-packet.c
When SSHKeepAlive is enabled, dropbear idletimeout is not working as expected.
> Idle Timeout Not working, when keepalive is enabled

- common-algo.c
- libtomcrypt/src/headers/tomcrypt_dropbear.h
- session.h
LibTomCrypt CBC support depends on CTR, symmetric_CBC is being unconditionally referenced even when DROPBEAR_ENABLE_CBC_MODE is disabled, it causes unnecessary compiled code and build errors when DROPBEAR_ENABLE_CRT_MODE is disabled.
Commit 4122cac66b139492d5b7fa6a1b8afcb1bfc529f7 has moved 3des-ctr into CBC group, it also causes build error with CBC the only mode w/o CTR enabled.
With both CBC & CTR modes disabled, cipher_state union may become empty which is not allowed by ISO C, it's better to have explicit check as it's already done for ciphers. So far no CTR/CBC is quite impossible scenario, but with new AEAD modes (Chacha20-Poly1305 and AES-GCM PR #93) both CBC and CTR may be safely disabled.
> CBC mode cleanup

- cli-kex.c
- common-kex.c
- dh_groups.c
- dh_groups.h
- kex.h
Reduces binary size by ~2kB by default and by 21kB with no other libtommath functions users, ex. with curve25519 kex and ed25519 key only.
> Allow DH to be completely disabled

- chachapoly.c
- gcm.c
On 32-bit platforms with old compiler STORE64H() parameter is not auto-expanded to 64-bit value, causing wrong IV data. Spotted on BCM4706 MIPS32r2 with GCC 4.2.4:
```Exit before auth: Integrity error (bad packet size 2065808956)```
Also, fix Chacha20-Poly1305 and AES-GCM trace debug messages, functions were renamed earlier and trace messages - not.
> Fix ChaCha20 on 32-bit platforms

- common-session.c
Per RFC4253 4.2 clients must be able to process other lines of data before the version string, server behavior is not defined neither with MUST/SHOULD nor with MAY.
Introducing commit d254e0191d27a98d09373b9df71ff3b13ffda092 (hg: ae4b1bdb29e60927c032674800f0258fc5966807) stated "no harm in letting the server handle it too", but if server process up to 50 lines too - it may cause too long hanging session with invalid/evil client that consume host resources and potentially may lead to DDoS on poor embedded boxes.
Let's require first line from client to be version string (since it's cheap) and fail early if it's not - matches both RFC and real OpenSSH behavior.
> Disallow leading lines before the ident for server

- cli-session.c
- svr-tcpfwd.c
The current code assumes that all global requests want / need a reply. This isn't always true and the request itself indicates if it wants a reply or not.
It causes a specific problem with `hostkeys-00@openssh.com` messages. These are sent by OpenSSH after authentication to inform the client of potential other host keys for the host. This can be used to add a new type of host key or to rotate host keys.
The initial information message from the server is sent as a global request, but with want_reply set to false. This means that the server doesn't expect an answer to this message. Instead the client needs to send a prove request as a reply if it wants to receive proof of ownership for the host keys.
The bug doesn't cause any current problems with due to how OpenSSH treats receiving the …
> Fix handling of replies to global requests

- cli-main.c
Moved pid_t proxy_cmd_pid declaration at begin of block to allow build in c89 (gcc-2.95)
> Update cli-main.c for C89

- netio.c
Moved allocated_lport_p and allocated_lport at begin of block to buld in C89
> Update netio.c for C89

- svr-tcpfwd.c
tcpip-forward request can include hostname, which is later resolved by getaddrinfo() call.
Dropbear incorrectly assumes tcpip-forward includes only IP(v4) address. Fix this.
> Use MAX_HOST_LEN for TCP forwarding requests

- dropbear.8
- runopts.h
- svr-chansession.c
- svr-runopts.c
The environment of the ssh server process is usually cleared and not passed on to the child process for security reasons. However, in certain situations it may be desirable to inherit the server environment. For example: I start dropbear (as non-root) from a SLURM workload manager, which exposes a lot variables containing of information about the confined runtime environment. These need to be inherited by child processes which are also subject to SLURM's runtime environment.
> pass on sever process environment to child processes (option -e)

- cli-auth.c
- cli-authinteract.c
- cli-authpasswd.c
- cli-authpubkey.c
- cli-runopts.c
- cli-session.c
- runopts.h
- session.h
I have added an option ``-o ExitOnTrivialAuth=yes`` to disable trivial authentications as discussed in our mails
> added option to disable trivial auth methods

- signkey.c
Remove the "!!" chars from message when printing the key-fingerprint, as it's confusing users (#116). They have been added when switching from MD5, but SHA1 can be considered as standard today.
> signkey: remove !! from SHA1 digest

- scp.c
This simply removes the following warning logged because the 6-th argument `int argc` is not used.
```
gcc -c -I./libtomcrypt/src/headers/ -I. -I.  -Os -W -Wall -Wno-pointer-sign -fno-strict-overflow -fPIE -fstack-protector-strong -D_FORTIFY_SOURCE=2 -DDROPBEAR_SERVER -DDROPBEAR_CLIENT  scp.c -o scp.o
scp.c: In function ‘do_cmd’:
scp.c:188:73: warning: unused parameter ‘argc’ [-Wunused-parameter]
188 | do_cmd(char *host, char *remuser, char *cmd, int *fdin, int *fdout, int argc)
|                                                                     ~~~~^~~~
```
> Remove unused argument of do_cmd() in scp.c

- svr-chansession.c
When gesftpserver is used as sftp server, it needs LANG variable to proper convert UTF-8 based filenames.
OpenSSH keep this variable for child process:
https://github.com/openssh/openssh-portable/blob/master/auth.c#L921
> keep LANG env variable for child process

- auth.h
- svr-authpubkey.c
- svr-authpubkeyoptions.c
- svr-chansession.c
This allows you to get the pubkey info in environment var SSH_PUBKEYINFO when a ssh key is used to gain access.
So for instance:
ssh_rsa AAAAB3Nz....DI0XQ== hans1_key
ssh_rsa AAAAB3Nz....XF7DF== appl1_key
After getting access with the second key, you get in SSH_PUBKEYINFO="appl1_key"
Very handy to recognize the remote appl/user when performing automatic actions.
> Pubkeyinfo

- cli-auth.c
- cli-authpasswd.c
- cli-authpubkey.c
- cli-main.c
- cli-runopts.c
- cli-session.c
- common-algo.c
- common-kex.c
- common-session.c
- dbutil.c
- dbutil.h
- debug.h
- default_options.h
Allows to specify multiple -v to increase verboseness of debug info
Keeps the TRACE and TRACE2 defines and adds additional DEBUG1, DEBUG2 and DEBUG3 defines
DEBUG_TRACE 1 = DEBUG1
DEBUG_TRACE 2 = DEBUG2
DEBUG_TRACE 3 = DEBUG3
DEBUG_TRACE 4 = TRACE
DEBUG_TRACE 5 = TRACE2
This way the least number of changes needs to be made to the code.
The most important change is the 3rd change, this does the defines in debug.h and changes in dbutil.c for the dropbear_traceX functions
Looks a lot better than the previous patch
The last 3 changes are for changing the TRACE info to DEBUG1, DEBUG2 and DEBUG3 defines for the dbclient
> Tracelevel2  

- svr-chansession.c
> Fix compilation when disabling pubkey authentication (DROPBEAR_SVR_PUBKEY_AUTH)

- svr-authpubkey.c
As per the message, even if I deleted the write permission(chmod -007), but an error occurred.
It's a source of confusion, so fix the message.
> Fix misleading error message

- cli-kex.c
When asking if continue connecting even if the fingerprint is not in the trusted hosts file, dbclient reads the first char from stdin but doesn't flush the text after until the newline. This causes the following prompt to fail automatically (for example the password prompt)
> Dbclient: Flush stdin after fingerprint confirmation

- loginrec.c
Fixed a typo error which arises when `UTMPX_USE_LIBRARY` is not defined
> Fix utx var typo

- cli-auth.c
As pointed out in the first comment in cli_auth_try function, the login methods order to try should be pubkey, interactive, password, while in the code the order is pubkey, password, interactive. This causes dbclient to skip `keyboard-interactive` login method. Resorting the methods seems to fix the issue.
> Dbclient: keyboard_interactive login method never used

- auth.h
- signkey.c
- signkey.h
- sk-ecdsa.c
- sk-ecdsa.h
- sk-ed25519.c
- sk-ed25519.h
- svr-authpubkey.c
- svr-authpubkeyoptions.c
This PR add support for no-touch-required and verify-required options for ecdsa-sk and ed25519-sk keys in authorized_keys file
Fixes #171
> Implement no-touch-required and verify-requred for authorized_keys file

- dropbear.8
- runopts.h
- svr-authpam.c
- svr-authpasswd.c
- svr-authpubkey.c
- svr-runopts.c
This patch introduces two-factor authentication to require both password and pubkey authentication.
The two-factor authentication can be enabled with "-t" 
Background: We are using ssh in an environment where the security policy mandates multi-method authentication for SSH (both password and pubkey). Dropbear does currently not support this but this is defined in the RFC and supported by other mainstream SSH servers. Unfortunately the security policy cannot be changed.
The patch is kept very small and code flow is not changed when the -t option is not used to avoid any regressions. Only 1 new variable is introduced to keep track of the config setting. The existing variable `ses.authstate.authtypes` is  used to keep track of the successful authentications and a "partial success" message as …
> Two-factor authentication support (pubkey and password)

- sshpty.c
This allows non-root Dropbear to work even without devpts gid=5 mount option on Linux.
An alternative to PR #200 , leaving this for testing before merging
> Allow users's own gid in pty permission check

- src/dbmulti.c
The dropbearkey is partially compatible with ssh-keygen and can be used as an alias.
Closes: #263
> dropbearkey: add alias to ssh-keygen

- DEVELOPING.md
- FUZZER-NOTES.md
- INSTALL.md
- MULTI.md
- README.md
- SMALL.md
Split long sentences. Use a line per a sentence.
This changes should improve reading of the .md files without word wrapping.
Additionally it will make line-by-line diffs more clear
> Reformat Markdown files

- src/dropbearkey.c
The OpenSSH ssh-keygen allows to omit the -t and will use rsa by default. For a better compatibility and simplification do the same.
> dropbearkey: make rsa as a default value for -t

- src/dropbearkey.c
For a better interoperability with OpenSSH I want to have their interface working similarly.
When generating a key with ssh-keygen it saves the identity file e.g. id_rsa and its public key id_rsa.pub. To get a public key a user can just `cat id_rsa.pub`. 
But the dropbearkey stores only the identity file.
When you need to get a public key you can execute `dropbearkey -y` and it will extract a public key from the private. It also prints a fingerprint of the key.
In many scripts and tutorials it is removed with `dropbearkey -y -f ~/.ssh/id_ed25519 | grep "^ssh-"`
The `ssh-keygen -y` behaves similarly but it doesn't print a fingerprint but only a raw pubkey. You can use a separate command `ssh -l` to print a fingerprint.
Also the `ssh-keygen -C comment` allows to specify an email for the …
> dropbearkey: save a public key file .pub

- src/scp.c
Port of [bug fix in openssh scp](https://github.com/openssh/openssh-portable/commit/067263e84800c4b35f9bbbfafdd92aea493b6e0b) to not ftruncate non-regular files (i.e. FIFO or device node).
Original openssh bug is at https://bugzilla.mindrot.org/show_bug.cgi?id=1236
This will avoid abnormal termination errors.
> Don't ftruncate() non-regular files

- INSTALL.md
- Makefile.in
- src/default_options.h
- src/options.h
This makes it easier for distributions to patch the source directory, rather than needing to create localoptions.h in the build directory.
Makefile's OPTION_HEADERS is removed, the wildcard *.h covers it
> Use src/distrooptions.h as another source

- src/dbrandom.c
It is a CPU bottleneck.
Fixes #276 on github
> Remove /proc/timer_list as an entropy source

- manpages/dbclient.1
- src/cli-auth.c
- src/cli-kex.c
- src/cli-runopts.c
- src/runopts.h
> dbclient: support -o StrictHostKeyChecking

- channel.h
- default_options.h
- netio.c
- netio.h
- svr-session.c
- svr-tcpfwd.c
- tcpfwd.h
VSCode remote ssh plugin need to create port forward between local port and remote unix socket, which is not yet support by current version of dropbear, this patch add a simple impl of port forwarding to local stream, only test on centos, debian x64, should work on any other linux variant. Any advice is welcome, thanks.
> Add function to port forward to local stream to support VSCode remote ssh target.

- src/cli-runopts.c
Fix build when `#define DROPBEAR_CLI_PUBKEY_AUTH 0`:
```
src/cli-runopts.c: In function ‘multihop_passthrough_args’:
src/cli-runopts.c:570:29: error: ‘cli_runopts’ has no member named ‘privkeys’
570 |         for (iter = cli_opts.privkeys->first; iter; iter = iter->next)
|                             ^
```
> cli-runopts.c add missing DROPBEAR_CLI_PUBKEY_AUTH

- .github/workflows/build.yml
- src/cli-readconf.c
- src/dbutil.c
- src/dbutil.h
Otherwise off-by-default features mightn't get checked properly
> Set more config options when building c89

- src/sysoptions.h
Allow defining version part of the ident string in localoptions.h, as suggested in the other PR.
> sysoptions.h: make version optional in ident string

- src/cli-runopts.c
Commit 12ab8ff5 added a check requiring a hostname, but it's before the ciphers and macs are checked.  This breaks "dbclient -m help" unless a hostname is also provided.
> Fix dbclient -m help and -c help w/out hostname.

- configure
- configure.ac
Use the AS_HELP_STRING macro for all options to ensure consistent and properly aligned help messages.
> Use AS_HELP_STRING and simplify bundled-libtom option

- src/svr-auth.c
https://github.com/mkj/dropbear/pull/83 removed the host from the final message part of early exit messages, and added it to the initial message part instead. This was however done for "Login attempt for nonexistent user" as well, which is no early exit message, but allows the client to keep trying. Those log entries hence now do not contain a host anymore.
This PR reverts this part of https://github.com/mkj/dropbear/pull/83 to restore the missing host, and re-enable software like Fail2Ban to track these login failures.
___________
As mentioned in #83, I guess "Login attempt with wrong user" (when Dropbear runs as non-root user) is no early exit message as well, and hence needs to be reverted the same way. Probably someone can verify this quicker than me.
> Re-add host to "Login attempt for nonexistent user" log

- src/common-channel.c
If check_close() ran prior to a server channel exec/shell request, it would send a close immediately.
This fix changes it to exclude write_fd==FD_UNINIT from being closed there.
When a channel was closed by the time shell/exec request was received, then data sent hits an assertion.
This fixes #321 on Github.
The "pid == 0" check was initially added to avoid waiting to close a channel when a process has never been launched (which is correct), but that isn't correct in the case of the closed-fd test.
Fixes: 8e6f73e879ca ("- Remove "flushing" handling for exited processes)
> Don't close channels when a PID hasn't started

- src/cli-runopts.c
- src/common-kex.c
- src/runopts.h
- src/session.h
- src/svr-runopts.c
Disable zlib entirely for server in the client to server direction. This avoids attack surface for zlib, and also saves 35kB runtime RAM for the decompression context. Interactive sessions don't have much traffic in the client->server direction so performance difference should not be noticable.
> Split compression s2c/c2s, disable server c2s

- manpages/dropbear.8
- src/dbutil.c
- src/dbutil.h
- src/runopts.h
- src/svr-authpubkey.c
- src/svr-runopts.c
This adds a "-D" option to dropbear which allow specifying the directory path where authorized_keys is located.  This will allow, for example running dropbear for interop testing during OpenSSH regression tests without impacting the running user's authorization files.
> Allow specifying authorized_keys directory.

- src/sysoptions.h
Should save maybe a few hundred bytes with bundled libtomcrypt
> Only include necessary ECC curves in libtomcrypt

- src/cli-session.c
Previously the hostkey mismatch error would be truncated.
> Increase buffer size for exit messages.

- src/svr-auth.c
As discussed and fixed in #316 for "nonexistent user" logs, this commit additionally reverts #83 for "wrong user" logs, to re-add the remote host to the those log entries.
> Re-add host to "Login attempt with wrong user" log

- configure
- configure.ac
Currently, if `htole64` is available on a platform as a macro in `endian.h` or `sys/endian.h` the `AC_CHECK_DECL` test does not detect them as they are not included in it.  As those two headers are however included in the build this causes the declarations of the compat functions to be mangled by the undetected macros and fail to compile.
Resolve this by passing conditional includes of `endian.h` and `sys/endian.h` to the includes parameter of the `AC_CHECK_DECL` macro so that the `htole64` macro is detected correctly.
(I found this when attempting to cross compile 2025.87 for Android where `htole64` is a macro defined in `sys/endian.h`.)
> Fix build when htole64 and related macros are defined in endian.h or sys/endian.h

- configure
- configure.ac
- src/config.h.in
- src/includes.h
Older uClibc (< ~1.0.42) or older compilers don't support static_assert
Fixes #351
> Test for static_assert

- src/compat.c
**Problem**
Older versions of GCC (e.g., 4.6.4) report a type incompatibility error due to the way `&out.bytes` is passed to `STORE64L` and `STORE32L`.
```
src/compat.c: In function 'htole64':
src/compat.c:291:2: error: incompatible types when assigning to type 'uint8_t[8]' from type 'unsigned char'
```
`out.bytes` is an array (`uint8_t[8]` for `htole64`, `uint8_t[4]` for `htole32`).
`&out.bytes` produces `uint8_t (*)[8]` (`uint8_t (*)[4]` for `htole32`), which does not match the expected `uint8_t*` parameter in `STORE64L` and `STORE32L`.
Newer compilers (e.g., GCC 4.8.5+) are more lenient, but older versions enforce strict type checking, leading to compilation errors.
**Solution**
Instead of passing `&out.bytes,` we pass `out.bytes` directly. This ensures proper type decay from an array …
> Fix type incompatibility in htole64 and htole32 with older GCC versions

- src/default_options.h
The path for distribution customizations is src/distrooptions.h, not src/distoptions.h.
This minor typo was added in 454591d (Use src/distrooptions.h as another source, 2024-01-22).
> Fix reference to distrooptions.h in default_options.h

- src/common-channel.c
- src/sysoptions.h
Previously the channel window and increments were limited to 500MB. That is incorrect and causes stuck connections if peers advertise a large window, then don't send an increment within the first 500MB.
That's seen with SSH.NET https://github.com/sshnet/SSH.NET/issues/1671
Fixes #376
> Don't limit channel window to 500MB

- src/svr-authpubkey.c
fixes:
- 98ef42a856 "Don't set pubkey_info directly in checkpubkey_line"
- 62ea53c1e5 "Implement no-touch-required and verify-requred for authorized_keys file"
> fix build without pubkey options
